'use strict';

function genName () {
    const name = data.userNames[Math.floor((Math.random() * data.userNames.length))];
    return name;

}

function genSurname () {
    const surname = `${data.userSNames[Math.floor((Math.random() * data.userSNames.length))]}${Math.random() < 0.8 ? ` ${data.userSNames[Math.floor((Math.random() * data.userSNames.length))]}` : ``}`;
    return surname;
}

function genRoomName () {
    const name = data.roomNames[Math.floor((Math.random() * data.roomNames.length))];
    return `${name}`;

}

function genCafeName () {
    const name = data.cafeNames[Math.floor((Math.random() * data.cafeNames.length))];
    const adj = data.cafeAdj[Math.floor((Math.random() * data.cafeAdj.length))];
    return `${adj} ${name}`;

}

const data = {
    userNames: [
        `Amadeus`,
        `André`,
        `Antônio`,
        `Antônia`,
        `Bruno`,
        `Bruna`,
        `César`,
        `Caio`,
        `Cissa`,
        `Daniel`,
        `Daniela`,
        `Eduardo`,
        `Eduarda`,
        `Francisco`,
        `Franciele`,
        `Gabriel`,
        `Gabriele`,
        `Giselle`,
        `Horácio`,
        `Ivan`,
        `Ivana`,
        `Isabel`,
        `Isadora`,
        `Isaque`,
        `Jaqueline`,
        `Jackson`,
        `Jax`,
        `Júlia`,
        `Júlio`,
        `José`,
        `João`,
        `Joaquim`,
        `Juarez`,
        `Jorge`,
        `Jéssica`,
        `Joana`,
        `Jade`,
        `Janaina`,
        `Kira`,
        `Karen`,
        `Kevin`,
        `Kael`,
        `Kaique`,
        `Kauã`,
        `Luciano`,
        `Luciana`,
        `Leo`,
        `Laísa`,
        `Laura`,
        `Larissa`,
        `Letícia`,
        `Lucas`,
        `Leonardo`,
        `Leandro`,
        `Lúcifer`,
        `Maria`,
        `Mauro`,
        `Márcia`,
        `Miguel`,
        `Matheus`,
        `Marcos`,
        `Natan`,
        `Natalia`,
        `Nicholas`,
        `Nicolau`,
        `Nisa`,
        `Osvaldo`,
        `Otávio`,
        `Olímpia`,
        `Otaviano`,
        `Paulo`,
        `Paulina`,
        `Pedro`,
        `Roberto`,
        `Reinaldo`,
        `Roberta`,
        `Rogério`,
        `Sofia`,
        `Sara`,
        `Sérgio`,
        `Samuel`,
        `Talita`,
        `Tiago`,
        `Tadeu`,
        `Vitor`,
        `Victario`,
        `Vilmar`
    ],
    userSNames: [
        `Abreu`,
        `Aguiar`,
        `Albuquerque`,
        `Alvarez`,
        `Brito`,
        `Barroso`,
        `Barbosa`,
        `Barcelos`,
        `Batista`,
        `Borges`,
        `Campos`,
        `Cabral`,
        `Calegari`,
        `Camargo`,
        `Campos`,
        `Caprini`,
        `Carnielli`,
        `Cassini`,
        `Duque`,
        `Dutra`,
        `Esteves`,
        `Eigenheer`,
        `Esteves`,
        `Ferreira`,
        `Falcheto`,
        `Faroni`,
        `Fiorini`,
        `Fraga`,
        `Freire`,
        `Frizzo`,
        `Guerra`,
        `Granzotto`,
        `Hansen`,
        `Harper`,
        `Henrichsen`,
        `Hoffman`,
        `Intriger`,
        `Johansen`,
        `Jorgensen`,
        `Kiefer`,
        `Kriesten`,
        `Leite`,
        `Lacerda`,
        `Larsen`,
        `Lisboa`,
        `Lorenzini`,
        `Loreto`,
        `Machado`,
        `Miranda`,
        `Mesquita`,
        `Marianelli`,
        `Marini`,
        `Marques`,
        `Nogueira`,
        `Noronha`,
        `Novaes`,
        `Oliveira`,
        `Olausdatter`,
        `Pereira`,
        `Partelli`,
        `Pedrazini`,
        `Pitanga`,
        `Prado`,
        `Queiroz`,
        `Quaresma`,
        `Rodrigues`,
        `Rabello`,
        `Ribeiro`,
        `Rios`,
        `Risther`,
        `Rocha`,
        `Rodrigues`,
        `Romanini`,
        `Santos`,
        `Silva`,
        `Sacramento`,
        `Salgado`,
        `Sandrini`,
        `Schneider`,
        `Soares`,
        `Souza`,
        `Tavares`,
        `Teixeira`,
        `Toledo`,
        `Torres`,
        `Trindade`,
        `Vasconcelos`,
        `Viana`,
        `Varandas`,
        `Vargas`,
        `Vicente`,
        `Weiss`,
        `Werner`,
        `Xavier`,
        `Zamparoni`,
        `Zandonadi`,
        `Zanoni`,
    ],
    cafeAdj: [
        `Cantina`,
        `Cantinho do`,
        `Pedaço de`,
        `Praça`,
        `Lanchonete`,
        `Hamburgueria`,
        `Sushi`,
        `Espeto`,
        `Churrascaria`,
        `Pizzaria`,
        `Castelinho`
    ],
    cafeNames: [
        `Tokyo`,
        `Tigre`,
        `Coxinha`,
        `Natureza`,
        `Europa`,
        `America`,
        `Figueira`,
        `Terra`,
        `São Paulo`,
        `Pão e Vinho`,
        `Mama Mia`,
        `Fogo de Chão`,
        `Carvão`
    ],
    roomNames: [
        `Alaska`,
        `Canada`,
        `Segunda`,
        `Terça`,
        `Quarta`,
        `Quinta`,
        `Sexta`,
        `Brasil`,
        `Don Quixote`,
        `França`,
        `Espanha`,
        `Italia`,
        `Alemanha`,
        `Medicina`,
        `Advocacia`,
        `Radialismo`
    ]
};

module.exports.userName = genName;
module.exports.userSName = genSurname;
module.exports.roomName = genRoomName;
module.exports.cafeName = genCafeName;
